apply plugin: 'com.android.library'

android {
    namespace "com.termux.tasker"

    compileSdk project.properties.compileSdkVersion.toInteger()

    defaultConfig {
        minSdk project.properties.minSdkVersion.toInteger()
        targetSdk project.properties.targetSdkVersion.toInteger()

        manifestPlaceholders.TERMUX_PACKAGE_NAME = "com.termux.merged"
        manifestPlaceholders.TERMUX_APP_NAME = "Termux"
        manifestPlaceholders.TERMUX_TASKER_APP_NAME = "Termux:Tasker"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true

        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:1.1.5"

    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "androidx.annotation:annotation:1.9.1"
    implementation "com.google.android.material:material:1.12.0"
    implementation "com.google.guava:guava:24.1-jre"

    implementation project(":termux-shared")

    implementation "com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava"

    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
            because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
            because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
        }
    }
}
