package com.termux.app.update;

import androidx.annotation.Nullable;

/**
 * Parsed shape of the JSON document {@link UpdateChecker} fetches from the URL the user
 * configures in the Plugins screen's Updates section. Expected fields:
 *
 * <pre>{@code
 * {
 *   "version_code": 119,
 *   "version_name": "0.119.0-merged",
 *   "apk_url": "https://example.com/releases/termux-merged.apk",
 *   "sha256": "6f1ed...",           // optional but strongly recommended, hex-encoded
 *   "notes": "what changed"          // optional
 * }
 * }</pre>
 *
 * There's no fixed hosting requirement -- this can be a static JSON file next to a GitHub
 * Releases asset, something generated by a CI job, anything. The app just needs a URL to it.
 */
public class UpdateManifest {
    public final int versionCode;
    public final String versionName;
    public final String apkUrl;
    @Nullable public final String sha256;
    @Nullable public final String notes;

    public UpdateManifest(int versionCode, String versionName, String apkUrl, @Nullable String sha256, @Nullable String notes) {
        this.versionCode = versionCode;
        this.versionName = versionName;
        this.apkUrl = apkUrl;
        this.sha256 = sha256;
        this.notes = notes;
    }
}
